import gin
import torch.optim as optim

gin.external_configurable(optim.Adadelta)
gin.external_configurable(optim.Adagrad)
gin.external_configurable(optim.Adam)
gin.external_configurable(optim.AdamW)
gin.external_configurable(optim.Adamax)
gin.external_configurable(optim.ASGD)
gin.external_configurable(optim.LBFGS)
gin.external_configurable(optim.RMSprop)
gin.external_configurable(optim.Rprop)
gin.external_configurable(optim.SGD)
gin.external_configurable(optim.SparseAdam)
gin.external_configurable(optim.lr_scheduler.CyclicLR)
gin.external_configurable(optim.lr_scheduler.ExponentialLR)
gin.external_configurable(optim.lr_scheduler.LambdaLR)
gin.external_configurable(optim.lr_scheduler.MultiStepLR)
gin.external_configurable(optim.lr_scheduler.OneCycleLR)
gin.external_configurable(optim.lr_scheduler.ReduceLROnPlateau)
gin.external_configurable(optim.lr_scheduler.StepLR)
gin.external_configurable(optim.lr_scheduler.CosineAnnealingLR)
gin.external_configurable(optim.lr_scheduler.CosineAnnealingWarmRestarts)
gin.external_configurable(optim.lr_scheduler.ConstantLR)
gin.external_configurable(optim.lr_scheduler.ExponentialLR)
gin.external_configurable(optim.lr_scheduler.PolynomialLR)
gin.external_configurable(optim.lr_scheduler.ReduceLROnPlateau)
gin.external_configurable(optim.lr_scheduler.MultiplicativeLR)
gin.external_configurable(optim.lr_scheduler.LinearLR)
gin.external_configurable(optim.lr_scheduler.ChainedScheduler)
gin.external_configurable(optim.lr_scheduler.LRScheduler)
